### ISSUE TITLE
ImportError: cannot import name 'izip' from 'itertools' (unknown location)

### ISSUE THREAD

**Issue by caity-s** [sufforest/SolidBin#5]
Hello,

I am looking forward to trying SolidBin! However, I'm having problems with the conda installation. I followed the instructions

```
git clone https://github.com/sufforest/SolidBin
cd SolidBin
conda env create -f environment.yml
conda activate solidbin
```
Which went smoothly, but I when trying to determine the composition I ran into an import problem:

```
python scripts/gen_kmer.py 
Traceback (most recent call last):
  File "scripts/gen_kmer.py", line 10, in <module>
    from itertools import tee, izip
ImportError: cannot import name 'izip' from 'itertools' (unknown location)
```
Do you have suggested solution?
Thank you,
Caitlin

**Comment by ziyewang** [comment]
We have fix the bug, you can download the latest version and have a try.

**Comment by lowspace** [comment]
> We have fix the bug, you can download the latest version and have a try.

Hi, I have met the same issue in another package, but the author seems to be away from this package. Could u please tell me how to solve this issue?

**Comment by shrinivas96** [comment]
Hi @lowspace. I face the same problem. It seems Python 3 does not have/need `itertools.izip()`. The solution seems to be to replace `izip(...)` with `zip(...)`.
