### ISSUE TITLE
Key Error when seed contig is 1000 bp long

### ISSUE THREAD

**Issue by Vini2** [sufforest/SolidBin#6]
When building the composition profiles, by default SolidBin keeps contigs longer than 1000 bp. However, when running `test_getmarker.pl` to get the seeds, the minimum contig length is set to 1000 bp. I came across a case where I got a seed contig which is 1000 bp long but its composition profile was not created. This resulted in a Key Error at line `304`. So I think the minimum contig length should be set to 1001 in line `141` of `SolidBin.py`. Setting the minimum contig length to 1001 solved the Key Error. Please correct me if I'm wrong.

Thank you!

**Comment by ziyewang** [comment]
I think that you are correct. Thanks very much.

Best,
ziye
